# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: A developer's diary
author:
  name: Zac (Zaccheo Bagnati)
  email: zaccheob@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Experiences and experiments of a software developer written mainly for myself
  and then for whoever may consider them useful.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zaccheob.github.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# This is to use minima v3 (still not released). Note that I'm binding to a specific commit to make it stable
remote_theme: jekyll/minima@2863624b903b17f838d6ce8d2f77900fa9d3c864

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/zaccheob" }
    # - { platform: twitter,  user_url: "https://twitter.com/zaccheob" }
    - { platform: linkedin,  user_url: "https://linkedin.com/in/zaccheo-bagnati" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/1221137/zac" }
    # - { platform: mastodon, user_url: "https://mastodon.uno/@zaccheo" }
    - { platform: strava, user_url: "https://www.strava.com/athletes/20594103" }

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
